/**
 * Created by: Edward Atencio
 * Created on: 18/09/19 (dd/mm/yy)
 */

namespace UnityEditorTools.PackageExporter
{
    public static class LoremIpsum
    {
        public static string text = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus velit, lobortis vel eros ac, vulputate auctor orci. Aenean interdum fermentum nisi, ac interdum magna. Aliquam a pulvinar turpis. Fusce sed neque vel nunc suscipit dapibus. Curabitur varius velit eleifend est laoreet, sed pretium ex dapibus. Nullam faucibus tortor sed urna cursus, congue fringilla metus luctus. Ut at ipsum sem. Proin ut mi in ipsum laoreet auctor. Donec ultricies non ligula auctor pellentesque. Etiam at orci sapien. Maecenas sit amet posuere lorem, scelerisque pharetra sapien. Etiam consequat est et lacus tristique cursus. Nulla imperdiet mollis mauris, quis venenatis lacus. Cras pretium elit quam, eget aliquam ligula scelerisque sit amet. Mauris vel massa id orci molestie volutpat. Etiam placerat urna in pellentesque ornare.

Sed in nunc ac ipsum egestas molestie ac eu urna. Morbi dictum imperdiet orci ut viverra. Pellentesque leo enim, blandit ac pretium eu, imperdiet eget ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc ac urna at turpis iaculis semper. Duis faucibus lectus odio, consectetur sollicitudin dolor ultrices at. Cras eget justo in ipsum congue mattis. Phasellus lobortis sem nisl, at tincidunt odio scelerisque sit amet. Fusce tempus facilisis dolor, a varius tortor suscipit nec. Aliquam erat volutpat. Curabitur tincidunt leo quis gravida tincidunt. Suspendisse dui nulla, commodo a porttitor feugiat, bibendum sit amet velit. Curabitur fringilla aliquam lorem sit amet placerat. Vivamus non ipsum eu ex consequat interdum. In euismod pretium neque, sit amet rhoncus felis bibendum ac. Nulla facilisi.

Sed ullamcorper libero ut consequat finibus. Quisque nibh sapien, pulvinar et hendrerit et, mattis non urna. Quisque tincidunt nunc eu mauris lobortis, id luctus ex imperdiet. Morbi sit amet finibus velit. Suspendisse a turpis turpis. Duis vestibulum ullamcorper nulla sit amet consectetur. Cras sit amet eros et augue scelerisque suscipit. Donec malesuada turpis libero, vel varius lectus sagittis nec. Nunc sed nulla vel quam euismod volutpat. Sed at velit faucibus, pharetra quam tincidunt, pellentesque metus. Nulla facilisi. Vestibulum fermentum tortor sem. Ut suscipit vel arcu et consectetur. Quisque id risus eget ligula pharetra mattis.

Vivamus vitae vestibulum risus, vel consequat nisi. Donec sapien dui, consectetur in tellus eu, ullamcorper ullamcorper elit. Integer eu neque lacinia, tincidunt tortor mattis, feugiat tellus. Maecenas accumsan in ex vitae interdum. Phasellus finibus erat massa, eget maximus metus aliquet nec. Etiam vitae orci urna. Duis et rhoncus enim. Morbi ac ligula et justo pellentesque scelerisque. Maecenas euismod finibus justo, a tincidunt mauris sodales eu. Proin id libero a odio maximus aliquet. Sed commodo, ligula sit amet lobortis dapibus, risus felis lacinia justo, et venenatis lorem augue id justo. Nam facilisis scelerisque nulla, ut euismod justo tincidunt ac. Nulla vehicula pharetra venenatis. Fusce pellentesque interdum massa, nec dapibus libero dapibus vitae. Vestibulum ut eros sit amet lacus sodales pellentesque placerat a neque. Integer nisi orci, porta quis lectus id, gravida dictum sem.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla facilisi. Nulla dapibus erat quis viverra volutpat. Curabitur et felis nec velit condimentum blandit. Proin pulvinar placerat mi id tempus. Duis congue neque vel nulla tristique gravida. Sed in nunc dignissim, blandit ipsum eget, aliquet augue. In nec sapien vel lectus tincidunt pulvinar. Ut porta justo et dapibus convallis. Donec condimentum ac lorem quis sagittis. Integer finibus, nibh sit amet fermentum ullamcorper, eros odio venenatis sem, interdum fermentum augue velit et enim. Donec sit amet sodales leo, quis consectetur neque. Mauris quis luctus magna. Morbi imperdiet justo ut augue cursus vestibulum. Proin accumsan, libero ac placerat dapibus, neque orci vulputate est, non auctor nunc metus a est. Integer molestie sed purus eget scelerisque.";
    }
}
